name: Validate YAML Syntax
on:
  pull_request:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate YAML syntax
      run: |
        set -e
        for file in $(find . -name "*.yaml" -o -name "*.yml"); do
          echo "Validating $file"
          yq eval-all "." $file 
        done

