name:  Pre-Deployment Validation
on: 
  workflow_dispatch:
  pull_request:
   types: [opened, reopened, synchronize]

jobs:
  validate:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}
      
      - name: List PRs
        env: # Or as an environment variable
          GIT_TOKEN: ${{ github.token }}
          LIST_FILES_IN_PR: ${{ steps.list-files.outputs.pullRequestFiles }}
        uses: ./.github/actions/validate
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - id: files
        #https://github.com/jitterbit/get-changed-files#get-all-removed-files-as-json
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
         sudo snap install yq

         readarray -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Files that are added or modified:  ${added_modified_file}."
            for filename in $(echo ${added_modified_file} | tr ',' '\n'); do
              echo "Processing $filename"
              yq eval-all "." $filename
              # perform your operations on $filename here
            done
          done
#          for file in ${added_modified_file[@]};do
 #           echo "Validating: $file"
  #          yq eval-all "." $file 
   #       done
