name: Validate YAML Syntax
on:
  pull_request:
    branches: [master]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate YAML syntax
      run: |
        set -e
        for file in $(ls *.yaml); do
          kubectl apply --dry-run=client --validate=true -f $file
        done
