name:  Pre-Deployment Validation
on: 
  workflow_dispatch:
  pull_request:
   types: [opened, reopened, synchronize]

jobs:
  validate:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Validate YAML syntax
        env: 
          GIT_TOKEN: ${{ github.token }}
        run: |
          pip3 install requests
          python3 ./.github/actions/PR_created.py
          set -e
          snap install yq
          for file in ${{ steps.list-files.outputs.pullRequestFiles }}; do
            echo "Validating $file"
            yq eval-all "." $file 
          done
