name:  Pre-Deployment Validation
on: 
  workflow_dispatch:
  pull_request:
   types: [opened, reopened, synchronize]

jobs:
  validate:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ github.token }}

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - id: files
        #https://github.com/jitterbit/get-changed-files#get-all-removed-files-as-json
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
         sudo snap install yq
         readarray -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for file in "${added_modified_files[@]}"; do
            file_arr = (${file})
            first = ${file_arr[0]}
            echo "Files that are added or modified:  $first."
          done
          
#          for file in ${added_modified_file[@]};do
 #           echo "Validating: $file"
  #          yq eval-all "." $file 
   #       done
